# Generated by Django 4.2.11 on 2026-02-22 00:00

from django.db import migrations, models
import django.db.models.deletion


def migrate_category_names_to_fk(apps, schema_editor):
    Transaction = apps.get_model('transactions', 'Transaction')
    Category = apps.get_model('categories', 'Category')

    for transaction in Transaction.objects.select_related('budget__user').all():
        name = getattr(transaction, 'category_name', None)
        if not name:
            continue
        normalized = name.strip()
        if not normalized:
            continue
        user = transaction.budget.user
        category = Category.objects.filter(user=user, name__iexact=normalized).first()
        if category is None:
            category = Category.objects.create(user=user, name=normalized)
        transaction.category = category
        transaction.save(update_fields=['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        ('categories', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='category',
            new_name='category_name',
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='transaction_category_not_blank',
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='transactions',
                to='categories.category',
            ),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(migrate_category_names_to_fk, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='transaction',
            name='category_name',
        ),
    ]
