# Generated by Django 4.2.11 on 2026-02-22 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_category_fk_description'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_budget__7b13c7_idx',
            old_name='transactio_budget_37c3ea_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_budget__1ec384_idx',
            old_name='transactio_budget_1b0b3d_idx',
        ),
    ]
