# Generated by Django 4.2.11 on 2026-02-22 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tokenblacklist'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tokenblacklist',
            new_name='token_black_token_6a50c6_idx',
            old_name='token_blacklist_token_idx',
        ),
    ]
