# Generated by Django 4.2.11 on 2026-02-22 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['name'],
                'indexes': [
                    models.Index(fields=['user'], name='categories_user_id_93a3c7_idx'),
                    models.Index(fields=['user', 'name'], name='categories_user_id_2f9b60_idx'),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(
                django.db.models.functions.Lower('name'),
                'user',
                name='unique_category_name_per_user'
            ),
        ),
    ]
