# Generated by Django 4.2.11 on 2026-02-22 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='category',
            new_name='categories_user_id_1cc1e0_idx',
            old_name='categories_user_id_93a3c7_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='categories_user_id_87930e_idx',
            old_name='categories_user_id_2f9b60_idx',
        ),
    ]
